-- MySQL Script generated by MySQL Workbench
-- Mon May 25 17:20:35 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema up
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema up
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `up` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `up` ;

-- -----------------------------------------------------
-- Table `up`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `up`.`user` (
  `USER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `up`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `up`.`post` (
  `POST_ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NOT NULL DEFAULT '-1',
  `DESCRIPTION` VARCHAR(1000) NULL DEFAULT NULL,
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `PHOTO_LINK` VARCHAR(300) NULL DEFAULT NULL,
  PRIMARY KEY (`POST_ID`),
  INDEX `USER_ID` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `post_ibfk_1`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `up`.`user` (`USER_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
